baseURL = 'https://devcast.pl/'

languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  version = '1.0.0'

[menus]
  [[menus.footer]]
    name = 'Legal'
    pageRef = '/legal'
    weight = 10
  [[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[taxonomies]
  author = 'authors'
  genre = 'genres'
